import numpy as np
from race_config import PanelArea, PanelEfficiency, RaceStartTime, RaceEndTime

# Constants
DT = RaceEndTime - RaceStartTime
_power_coeff = PanelArea * PanelEfficiency

def _calc_solar_irradiance(time: float) -> float:
    """Calculates solar irradiance at a given time using a Gaussian model.

    Args:
        time: Time in seconds from the start of the simulation.

    Returns:
        Solar irradiance in W/m^2.
    """
    return 1073.099 * np.exp(-0.5 * ((time - 43200) / 11600)**2)

def calculate_incident_solarpower(globaltime: np.ndarray, latitude: np.ndarray, longitude: np.ndarray) -> np.ndarray:
    """Calculates power generated by solar panels along the route.

    Args:
        globaltime: Array of cumulative time stamps in seconds.
        latitude: Array of latitudes along the route.
        longitude: Array of longitudes along the route.

    Returns:
        Array of incident solar power in Watts.
    """
    gt = globaltime % DT
    intensity = _calc_solar_irradiance(RaceStartTime + gt)
    return intensity * _power_coeff
